# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates the account
#'
#' @param spot \code{numeric} vector with the VA reference fund values
#' @param fee  \code{numeric} scalar with the fee
#' @param barrier \code{numeric} scalar with the state-dependent barrier
#' @export
calc_account <- function(spot, fee, barrier) {
    .Call('valuer_calc_account', PACKAGE = 'valuer', spot, fee, barrier)
}

