
#Notes for the pricer engine of a VA product
#Author: Ivan Zoccolan Date: 6/8/16


#PRODUCT
#The path_dependent class will be the base class of a VA product
#The cash_flows method needs to take into account the death time
#The death_time can be simulated by the VA pricer engine an passed to the cash_flows method
#A new path_dependent subclass is needed for each VA contract rider
#For example we will have a specialized GMAB path_dependent class for VA with GMAB rider, etc
#Will implement GMAB, GMDB and GMAB + GMDB first. Will leave GMIB, GMIB + GMDB, GMWB for a later stage.
#The cash_flows will return all possible withdrawal cash_flow. The engine will use the cash_flows
#depending if we're doing static or mixed
#The cash flows will be saved in private field of the engine.
#The formula which calculates the account cannot be vectorized since each value dependends on the
#previuos one. Take into consideration an implementation in C of that formula.

#ENGINE
#The engine should return both the static and mixed approach calculation
#It should since we want to compare results from both approaches applied to the same simulated paths
#Define a new base class va_engine and specialize it whenever we change the way we simulate the underlying asset
#(e.g Black Scholes va_bs_engine or jump diffusion va_jump_engine etc).
#The get_one_path method will generate the path which has to be saved into an internal matrix
#Need a  private field  with the underlying asset paths matrix

#If using stochastic interest rate the implementation of discounts active binding has to be changed.
#If we used as is  I would use a sample path for interest rate for discounting which would be different
#from the one used to generate the underlying asset path.
#So the get_one_path will generate also the interest rate path
#A private field with a matrix to hold the simulated interest rate paths needs to be added
#Each row of the matrix will hold a interest rate path
#get_one_path will populate both the asset path matrix and the interest rate path matrix.
#the discounts binding will return the discount factors (calculate the integrals) based on
#the interest rate paths saved in the private interest rate matrix.

#A private field of the engine needs to save the cash flows generated by the product.
#It will be a matrix where each row will save a cash flow path.

#VA pricer engine will have an active binding to simulate the death time.
#Implementation of the VA pricer must be changed if we want stochastic mortality or deterministic mortality.
#Deterministic will be the first choice.
#The pricer will pass the death time to the cash_flows method of the VA product so that it will return the
#cash_flows up to death time.




